name: Continuous Deployment
on:
    workflow_run:
        workflows: ["Continuous Integration"]
        types:
            - completed
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Deploy to HuggingFace
              env:
                HF: ${{ secrets.HUGGINGFACE_TOKEN }}
              run: make deploy-hf HUGGINGFACE_TOKEN=$HF